blank_issues_enabled: true
contact_links:
  - name: Enhancement or feature request
    url: https://github.com/mana-hq/mana-meta/discussions/categories/ideas
    about: Do you have a suggestion or feature request?
  - name: Mana Android Community Support
    url: https://matrix.to/#/#mana-android:matrix.org
    about: General Mana Android support questions can be asked in the app Matrix room
